# Generated by Django 5.1.4 on 2025-01-14 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_message_room_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_created_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
