# Generated by Django 5.1.4 on 2025-02-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.FileField(null=True, upload_to='messages_Image'),
        ),
    ]
