# Generated by Django 5.1.4 on 2025-02-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_message_content_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_image',
            field=models.BooleanField(default=False),
        ),
    ]
